[[OSQP_CUDA]]
arch = "x86_64"
git-tree-sha1 = "484564715120184b43046a64dafe4f1f8b623528"
lazy = true
libc = "glibc"
os = "linux"

    [[OSQP_CUDA.download]]
    sha256 = "8d145abd13b38310765edbaefd13447ad47bdb3ea5795b9a4b196a7b68b9c8fb"
    url = "https://github.com/osqp/OSQP_CUDA_jll.jl/releases/download/OSQP_CUDA-v100.0.0+0/OSQP_CUDA.v100.0.0.x86_64-linux-gnu.tar.gz"
