# Autogenerated wrapper script for OSQP_CUDA_jll for x86_64-linux-gnu-cxx11-cuda+11.4
export osqp_cuda_double, osqp_cuda_single

using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("OSQP_CUDA")
JLLWrappers.@declare_library_product(osqp_cuda_double, "libosqp_cuda_double.so")
JLLWrappers.@declare_library_product(osqp_cuda_single, "libosqp_cuda_single.so")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        osqp_cuda_double,
        "lib/libosqp_cuda_double.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        osqp_cuda_single,
        "lib/libosqp_cuda_single.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
